import React, { useState } from 'react';
import { ArrowLeft, CalendarDays, Check, ChevronRight, Clock3, Dumbbell, Flame, Minus, Play, Plus, Target, TrendingUp, Trophy, Weight } from 'lucide-react-native';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Avatar, Badge, Card, ProfilePhoto, SectionHeader, StatCard } from '../components/UI';
import { colors } from '../theme';
import { PlanWeek, Workout } from '../types';

export function StudentHome({ workouts, onStart, onWorkouts }: { workouts: Workout[]; onStart: (workout: Workout) => void; onWorkouts: () => void }) {
  const today = workouts[0];
  if (!today) return <ScrollView contentContainerStyle={styles.page}><Text style={styles.pageTitle}>Sua ficha está a caminho</Text><Text style={styles.pageDescription}>Seu personal ainda não publicou treinos para você.</Text></ScrollView>;
  return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
    <View style={styles.greeting}><View><Text style={styles.muted}>Olá, Lucas!</Text><Text style={styles.pageTitle}>Vamos treinar?</Text></View></View>
    <Card style={styles.workoutHero}><View style={styles.heroHead}><View><Text style={styles.heroEyebrow}>TREINO DE HOJE</Text><Text style={styles.heroTitle}>{today.title}</Text><Text style={styles.heroSubtitle}>{today.focus}</Text></View><View style={styles.dumbbellCircle}><Dumbbell size={25} color={colors.white}/></View></View><View style={styles.metaRow}><View style={styles.metaItem}><Clock3 size={15} color="#FFDCC8"/><Text style={styles.metaText}>{today.duration} min</Text></View><View style={styles.metaItem}><Target size={15} color="#FFDCC8"/><Text style={styles.metaText}>{today.exercises.length} exercícios</Text></View></View><Pressable style={styles.heroButton} onPress={() => onStart(today)}><Play size={18} color={colors.primary} fill={colors.primary}/><Text style={styles.heroButtonText}>Iniciar treino</Text><ChevronRight size={18} color={colors.primary}/></Pressable></Card>
    <SectionHeader eyebrow="SEU RITMO" title="Resumo da semana"/><View style={styles.statsRow}><StatCard icon={Dumbbell} value="4" label="treinos concluídos"/><StatCard icon={Flame} value="12" label="treinos em sequência" tone="amber"/><StatCard icon={TrendingUp} value="+8%" label="volume de treino" tone="dark"/></View>
    <SectionHeader eyebrow="AGENDA" title="Próximos treinos" action="Ver todos" onAction={onWorkouts}/>{workouts.slice(1).map((workout, index) => <Pressable key={workout.id} onPress={() => onStart(workout)}><Card style={styles.listCard}><View style={styles.listIcon}>{index === 0 ? <CalendarDays size={20} color={colors.primary}/> : <Dumbbell size={20} color={colors.primary}/>}</View><View style={styles.listCopy}><Text style={styles.listTitle}>{workout.title}</Text><Text style={styles.listSubtitle}>{workout.focus}</Text></View><Text style={styles.listMeta}>{workout.duration} min</Text><ChevronRight size={18} color={colors.subtle}/></Card></Pressable>)}
    <Card style={styles.coachNote}><View style={styles.noteHeader}><Avatar initials="BS" size={38}/><View><Text style={styles.noteLabel}>RECADO DO PERSONAL</Text><Text style={styles.noteName}>BS Personal</Text></View></View><Text style={styles.noteText}>“Sua execução melhorou bastante. Hoje, priorize o controle do movimento antes de aumentar a carga.”</Text></Card>
  </ScrollView>;
}

export function StudentWorkouts({ workouts, onStart }: { workouts: Workout[]; onStart: (workout: Workout) => void }) {
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.pageTitle}>Seus treinos</Text><Text style={styles.pageDescription}>Sua ficha atual, organizada pela BS Personal.</Text>{workouts.map((workout, index) => <Pressable key={workout.id} onPress={() => onStart(workout)}><Card style={styles.planCard}><View style={styles.planTop}><View style={styles.planIndex}><Text style={styles.planIndexText}>{String.fromCharCode(65 + index)}</Text></View><Badge label={index === 0 ? 'Hoje' : `${workout.duration} min`} tone={index === 0 ? 'orange' : 'gray'}/></View><Text style={styles.planTitle}>{workout.title}</Text><Text style={styles.planFocus}>{workout.focus}</Text><View style={styles.planFooter}><Text style={styles.planDetail}>{workout.exercises.length} exercícios · {workout.level}</Text><View style={styles.roundButton}><ChevronRight size={18} color={colors.primary}/></View></View></Card></Pressable>)}</ScrollView>;
}

export function StudentPlan({ weeks }: { weeks: PlanWeek[] }) {
  const [selectedId, setSelectedId] = useState(weeks[0]?.id);
  const selected = weeks.find((week) => week.id === selectedId) ?? weeks[0];
  if (!selected) return null;
  const intensityColor = selected.intensity === 'Alta' ? colors.red : selected.intensity === 'Moderada' ? colors.primaryDark : colors.green;
  return <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
    <Text style={styles.pageTitle}>Seu plano</Text><Text style={styles.pageDescription}>Seu ciclo de treino foi organizado pela BS Personal.</Text>
    <Card style={styles.planStatus}><View style={styles.planStatusIcon}><CalendarDays size={22} color={colors.primary}/></View><View style={styles.listCopy}><Text style={styles.planStatusLabel}>CICLO ATUAL · OUTUBRO</Text><Text style={styles.planStatusTitle}>Construção de força e hipertrofia</Text><Text style={styles.planStatusText}>4 semanas · acompanhamento semanal</Text></View></Card>
    <SectionHeader eyebrow="CRONOGRAMA" title="Semanas do ciclo"/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.weekSelector}>{weeks.map((week, index) => { const active = week.id === selected.id; return <Pressable key={week.id} onPress={() => setSelectedId(week.id)} style={[styles.weekPill, active && styles.weekPillActive]}><Text style={[styles.weekPillLabel, active && styles.weekPillLabelActive]}>{week.label}</Text><Text style={[styles.weekPillDate, active && styles.weekPillDateActive]}>{index + 1}/4</Text></Pressable>; })}</ScrollView>
    <Card style={styles.weekDetail}><View style={styles.weekDetailTop}><Badge label={selected.phase}/><Text style={styles.weekDate}>{selected.dateRange}</Text></View><Text style={styles.weekTitle}>{selected.label}: {selected.phase}</Text><Text style={styles.weekDescription}>{selected.description}</Text><View style={styles.weekMetrics}><View style={styles.weekMetric}><Dumbbell size={18} color={colors.primary}/><View><Text style={styles.weekMetricValue}>{selected.sessions} treinos</Text><Text style={styles.weekMetricLabel}>planejados</Text></View></View><View style={styles.weekMetric}><TrendingUp size={18} color={intensityColor}/><View><Text style={styles.weekMetricValue}>{selected.intensity}</Text><Text style={styles.weekMetricLabel}>intensidade</Text></View></View></View></Card>
    <SectionHeader eyebrow="ORIENTAÇÃO" title="Como executar esta semana"/><Card><Text style={styles.noteText}>As cargas devem respeitar a sensação de esforço e a técnica. Registre cada sessão para que a BS Personal possa ajustar a próxima semana.</Text></Card>
  </ScrollView>;
}

export function StudentProgress() {
  const bars = [42, 68, 52, 84, 70, 96];
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.pageTitle}>Sua evolução</Text><Text style={styles.pageDescription}>Progresso construído treino após treino.</Text><Card style={styles.highlight}><View style={styles.trophyIcon}><Trophy size={22} color={colors.amber}/></View><View style={styles.listCopy}><Text style={styles.highlightLabel}>NOVO RECORDE PESSOAL</Text><Text style={styles.highlightTitle}>Supino reto · 45 kg</Text><Text style={styles.highlightText}>10 repetições no último treino</Text></View></Card><SectionHeader eyebrow="CONSISTÊNCIA" title="Treinos por semana"/><Card><View style={styles.chartHeader}><View><Text style={styles.chartValue}>21 treinos</Text><Text style={styles.chartCaption}>nas últimas 6 semanas</Text></View><Badge label="+17%" tone="green"/></View><View style={styles.chart}>{bars.map((height, index) => <View style={styles.barColumn} key={index}><View style={[styles.bar, { height }, index === bars.length - 1 && styles.barActive]}/><Text style={styles.barText}>{['S1','S2','S3','S4','S5','S6'][index]}</Text></View>)}</View></Card><SectionHeader eyebrow="MEDIDAS" title="Últimos registros"/><View style={styles.measureGrid}><Card style={styles.measureCard}><Weight size={20} color={colors.primary}/><Text style={styles.measureValue}>78,4 kg</Text><Text style={styles.measureLabel}>Peso atual</Text><Text style={styles.measureDelta}>−2,1 kg desde julho</Text></Card><Card style={styles.measureCard}><TrendingUp size={20} color={colors.primary}/><Text style={styles.measureValue}>45 kg</Text><Text style={styles.measureLabel}>Supino reto</Text><Text style={styles.measureDelta}>+7,5 kg em 8 semanas</Text></Card></View></ScrollView>;
}

export function StudentProfile({ onLogout }: { onLogout: () => void }) {
  return <ScrollView contentContainerStyle={styles.page}><View style={styles.profileHeader}><ProfilePhoto size={72}/><Text style={styles.profileName}>Lucas Martins</Text><Text style={styles.pageDescription}>Aluno BS Personal desde maio de 2025</Text><Badge label="Objetivo: hipertrofia"/></View><SectionHeader title="Informações do acompanhamento"/><Card>{[['Altura', '1,78 m'], ['Peso atual', '78,4 kg'], ['Gordura corporal', '16,8%'], ['Próxima avaliação', '15 de outubro']].map(([label, value], index) => <View key={label} style={[styles.infoRow, index > 0 && styles.infoBorder]}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>)}</Card><SectionHeader title="Observações do personal"/><Card><Text style={styles.noteText}>Evitar exercícios com impacto alto no joelho direito. Priorizar mobilidade de quadril e controle da execução.</Text></Card><Pressable style={styles.logoutButton} onPress={onLogout}><Text style={styles.logoutText}>Sair da conta</Text></Pressable></ScrollView>;
}

export function WorkoutPlayer({ workout, onBack, onFinish }: { workout: Workout; onBack: () => void; onFinish: () => void }) {
  const [exerciseIndex, setExerciseIndex] = useState(0); const [completedSets, setCompletedSets] = useState(0); const exercise = workout.exercises[exerciseIndex]; const [load, setLoad] = useState(String(exercise.previous));
  const complete = () => { if (completedSets + 1 < exercise.sets) { setCompletedSets(completedSets + 1); return; } if (exerciseIndex + 1 < workout.exercises.length) { const next = workout.exercises[exerciseIndex + 1]; setExerciseIndex(exerciseIndex + 1); setCompletedSets(0); setLoad(String(next.previous)); return; } onFinish(); };
  const progress = ((exerciseIndex + completedSets / exercise.sets) / workout.exercises.length) * 100;
  return <SafeAreaView style={styles.playerSafe}><View style={styles.playerTop}><Pressable style={styles.backButton} onPress={onBack}><ArrowLeft size={21} color={colors.text}/></Pressable><View style={styles.playerTitleWrap}><Text style={styles.playerEyebrow}>{workout.title}</Text><Text style={styles.playerCounter}>{exerciseIndex + 1} de {workout.exercises.length} exercícios</Text></View><View style={styles.backButton}/></View><View style={styles.progressTrack}><View style={[styles.progressBar, { width: `${progress}%` }]}/></View><ScrollView contentContainerStyle={styles.playerPage}><View style={styles.videoBox}><View style={styles.videoIcon}><Play size={23} color={colors.white} fill={colors.white}/></View><Text style={styles.videoText}>Demonstração do exercício</Text></View><Badge label={exercise.group}/><Text style={styles.exerciseName}>{exercise.name}</Text><Text style={styles.exerciseNote}>Mantenha o movimento controlado e respeite o intervalo entre as séries.</Text><View style={styles.prescription}><View style={styles.prescriptionItem}><Text style={styles.prescriptionValue}>{exercise.sets}</Text><Text style={styles.prescriptionLabel}>Séries</Text></View><View style={styles.prescriptionItem}><Text style={styles.prescriptionValue}>{exercise.reps}</Text><Text style={styles.prescriptionLabel}>Repetições</Text></View><View style={styles.prescriptionItem}><Text style={styles.prescriptionValue}>{exercise.rest}</Text><Text style={styles.prescriptionLabel}>Descanso</Text></View></View><Text style={styles.loadLabel}>Carga desta série</Text><View style={styles.loadRow}><Pressable style={styles.loadButton} onPress={() => setLoad(String(Math.max(0, Number(load) - 1)))}><Minus size={20} color={colors.text}/></Pressable><TextInput value={load} onChangeText={setLoad} keyboardType="numeric" style={styles.loadInput}/><Text style={styles.kg}>kg</Text><Pressable style={styles.loadButton} onPress={() => setLoad(String(Number(load) + 1))}><Plus size={20} color={colors.text}/></Pressable></View><View style={styles.setsRow}>{Array.from({ length: exercise.sets }).map((_, index) => <View key={index} style={[styles.setCircle, index < completedSets && styles.setDone]}>{index < completedSets ? <Check size={15} color={colors.white}/> : <Text style={styles.setNumber}>{index + 1}</Text>}</View>)}</View></ScrollView><Pressable style={styles.completeButton} onPress={complete}><Text style={styles.completeText}>{completedSets + 1 < exercise.sets ? 'Concluir série' : exerciseIndex + 1 < workout.exercises.length ? 'Próximo exercício' : 'Finalizar treino'}</Text><ChevronRight size={19} color={colors.white}/></Pressable></SafeAreaView>;
}

const styles = StyleSheet.create({
  page: { paddingHorizontal: 20, paddingBottom: 110 }, greeting: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 5, marginBottom: 18 }, muted: { color: colors.muted, fontSize: 13 }, pageTitle: { color: colors.text, fontSize: 25, fontWeight: '800', letterSpacing: -0.7, marginTop: 2 }, pageDescription: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 4 }, workoutHero: { backgroundColor: colors.primary, borderColor: colors.primary, padding: 18 }, heroHead: { flexDirection: 'row', justifyContent: 'space-between' }, heroEyebrow: { color: '#FFE1D0', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, heroTitle: { color: colors.white, fontSize: 24, fontWeight: '800', marginTop: 7 }, heroSubtitle: { color: '#FFF0E8', fontSize: 13, marginTop: 4 }, dumbbellCircle: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#FFFFFF20', alignItems: 'center', justifyContent: 'center' }, metaRow: { flexDirection: 'row', gap: 18, marginTop: 19 }, metaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 }, metaText: { color: '#FFF0E8', fontSize: 11, fontWeight: '600' }, heroButton: { backgroundColor: colors.white, borderRadius: 14, padding: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: 18 }, heroButtonText: { color: colors.primaryDark, fontSize: 13, fontWeight: '800', flex: 1, textAlign: 'center' }, statsRow: { flexDirection: 'row', gap: 8 }, listCard: { flexDirection: 'row', alignItems: 'center', padding: 13, marginBottom: 10 }, listIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, listCopy: { flex: 1, marginLeft: 11 }, listTitle: { color: colors.text, fontSize: 13, fontWeight: '800' }, listSubtitle: { color: colors.muted, fontSize: 11, marginTop: 3 }, listMeta: { color: colors.muted, fontSize: 10, marginRight: 4 }, coachNote: { marginTop: 25, backgroundColor: '#FFFBF8', borderColor: colors.primaryBorder }, noteHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 }, noteLabel: { color: colors.primaryDark, fontSize: 9, fontWeight: '800', letterSpacing: .8 }, noteName: { color: colors.text, fontSize: 13, fontWeight: '800', marginTop: 2 }, noteText: { color: colors.muted, fontSize: 12, lineHeight: 19, marginTop: 12 },
  planCard: { marginTop: 13, padding: 17 }, planTop: { flexDirection: 'row', justifyContent: 'space-between' }, planIndex: { width: 38, height: 38, borderRadius: 13, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, planIndexText: { color: colors.white, fontSize: 15, fontWeight: '900' }, planTitle: { color: colors.text, fontSize: 20, fontWeight: '800', marginTop: 17 }, planFocus: { color: colors.muted, fontSize: 13, marginTop: 4 }, planFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 16 }, planDetail: { color: colors.muted, fontSize: 11 }, roundButton: { width: 32, height: 32, borderRadius: 12, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' },
  planStatus: { flexDirection: 'row', alignItems: 'center', marginTop: 21, backgroundColor: colors.primarySoft, borderColor: colors.primaryBorder }, planStatusIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: '#FFE0CF', alignItems: 'center', justifyContent: 'center' }, planStatusLabel: { color: colors.primaryDark, fontSize: 9, fontWeight: '800', letterSpacing: .7 }, planStatusTitle: { color: colors.text, fontSize: 14, fontWeight: '800', marginTop: 3 }, planStatusText: { color: colors.muted, fontSize: 11, marginTop: 3 }, weekSelector: { gap: 8, paddingRight: 20 }, weekPill: { minWidth: 78, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: colors.border }, weekPillActive: { backgroundColor: colors.primary, borderColor: colors.primary }, weekPillLabel: { color: colors.text, fontSize: 12, fontWeight: '800' }, weekPillLabelActive: { color: colors.white }, weekPillDate: { color: colors.muted, fontSize: 10, marginTop: 2 }, weekPillDateActive: { color: '#FFE5D5' }, weekDetail: { marginTop: 16 }, weekDetailTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, weekDate: { color: colors.muted, fontSize: 11 }, weekTitle: { color: colors.text, fontSize: 20, fontWeight: '800', marginTop: 16 }, weekDescription: { color: colors.muted, fontSize: 12, lineHeight: 19, marginTop: 7 }, weekMetrics: { flexDirection: 'row', gap: 10, borderTopWidth: 1, borderTopColor: colors.border, marginTop: 17, paddingTop: 15 }, weekMetric: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 }, weekMetricValue: { color: colors.text, fontSize: 12, fontWeight: '800' }, weekMetricLabel: { color: colors.muted, fontSize: 10, marginTop: 2 },
  highlight: { flexDirection: 'row', alignItems: 'center', marginTop: 21, backgroundColor: colors.amberSoft, borderColor: '#F7D994' }, trophyIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: '#FFF0C2', alignItems: 'center', justifyContent: 'center' }, highlightLabel: { color: '#9A6700', fontSize: 9, fontWeight: '800', letterSpacing: .7 }, highlightTitle: { color: colors.text, fontSize: 14, fontWeight: '800', marginTop: 3 }, highlightText: { color: colors.muted, fontSize: 11, marginTop: 2 }, chartHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' }, chartValue: { color: colors.text, fontSize: 21, fontWeight: '800' }, chartCaption: { color: colors.muted, fontSize: 11, marginTop: 2 }, chart: { height: 130, flexDirection: 'row', alignItems: 'flex-end', gap: 10, marginTop: 18 }, barColumn: { flex: 1, height: '100%', justifyContent: 'flex-end', alignItems: 'center' }, bar: { width: '100%', backgroundColor: '#FFD7C1', borderRadius: 7 }, barActive: { backgroundColor: colors.primary }, barText: { color: colors.muted, fontSize: 9, marginTop: 6 }, measureGrid: { flexDirection: 'row', gap: 10 }, measureCard: { flex: 1 }, measureValue: { color: colors.text, fontSize: 19, fontWeight: '800', marginTop: 10 }, measureLabel: { color: colors.muted, fontSize: 11, marginTop: 2 }, measureDelta: { color: colors.green, fontSize: 10, marginTop: 8, fontWeight: '700' },
  profileHeader: { alignItems: 'center', paddingTop: 12, paddingBottom: 10 }, profileName: { color: colors.text, fontSize: 22, fontWeight: '800', marginTop: 11 }, infoRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3 }, infoBorder: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 14, marginTop: 11 }, infoLabel: { color: colors.muted, fontSize: 12 }, infoValue: { color: colors.text, fontSize: 12, fontWeight: '700' }, logoutButton: { borderWidth: 1, borderColor: colors.primaryBorder, padding: 14, borderRadius: 14, alignItems: 'center', marginTop: 25 }, logoutText: { color: colors.primaryDark, fontSize: 13, fontWeight: '800' },
  playerSafe: { flex: 1, backgroundColor: colors.background }, playerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 15 }, backButton: { width: 40, height: 40, borderRadius: 14, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, playerTitleWrap: { alignItems: 'center' }, playerEyebrow: { color: colors.text, fontSize: 13, fontWeight: '800' }, playerCounter: { color: colors.muted, fontSize: 10, marginTop: 2 }, progressTrack: { height: 4, backgroundColor: colors.border }, progressBar: { height: 4, backgroundColor: colors.primary }, playerPage: { padding: 20, paddingBottom: 105 }, videoBox: { height: 185, borderRadius: 22, backgroundColor: colors.dark, alignItems: 'center', justifyContent: 'center', marginBottom: 20 }, videoIcon: { width: 52, height: 52, borderRadius: 18, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, videoText: { color: '#C8D0D9', fontSize: 10, marginTop: 10 }, exerciseName: { color: colors.text, fontSize: 25, lineHeight: 31, fontWeight: '800', marginTop: 10 }, exerciseNote: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 7 }, prescription: { flexDirection: 'row', gap: 8, marginTop: 20 }, prescriptionItem: { flex: 1, backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.border, alignItems: 'center', paddingVertical: 13 }, prescriptionValue: { color: colors.text, fontSize: 16, fontWeight: '800' }, prescriptionLabel: { color: colors.muted, fontSize: 9, marginTop: 3 }, loadLabel: { color: colors.text, fontSize: 12, fontWeight: '800', textAlign: 'center', marginTop: 25 }, loadRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 13, marginTop: 11 }, loadButton: { width: 42, height: 42, borderRadius: 15, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, loadInput: { color: colors.text, fontSize: 28, fontWeight: '800', width: 62, textAlign: 'right' }, kg: { color: colors.muted, marginLeft: -9 }, setsRow: { flexDirection: 'row', gap: 9, justifyContent: 'center', marginTop: 20 }, setCircle: { width: 31, height: 31, borderRadius: 16, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, setDone: { backgroundColor: colors.primary, borderColor: colors.primary }, setNumber: { color: colors.muted, fontSize: 11, fontWeight: '800' }, completeButton: { backgroundColor: colors.primary, marginHorizontal: 20, marginBottom: 14, height: 52, borderRadius: 15, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 4 }, completeText: { color: colors.white, fontSize: 14, fontWeight: '800' },
});
